dataplatform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: analytics
      password: analytics
      dbname: analytics
      schema: analytics
      port: 5432
