dataplatform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: platform
      password: platform
      dbname: warehouse
      schema: analytics
      port: 5432
